### ISSUE TITLE
INSTALL_FAILED_INSUFFICIENT_STORAGE

### ISSUE THREAD

**Issue by AaronMT** [ReactiveCircus/android-emulator-runner#184]
Hello,

```Log
API level: 28
target: google_apis
CPU architecture: x86_64
Hardware profile: pixel_3a
Cores: 2
RAM size: 
SD card path or size: 3072M
AVD name: test
force avd creation: true
emulator options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
disable animations: true
disable spellchecker: false
disable Linux hardware acceleration: true
```

Despite setting `sdcard-path-or-size`, I still seem to be getting `INSTALL_FAILED_INSUFFICIENT_STORAGE`

```Log
com.android.build.gradle.internal.testing.ConnectedDevice > runTests[test(AVD) - 9] FAILED 
	com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_INSUFFICIENT_STORAGE
		at com.android.build.gradle.internal.testing.ConnectedDevice.installPackage(ConnectedDevice.java:133)
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_INSUFFICIENT_STORAGE
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.android.ide.common.workers.ExecutorServiceAdapter.await(ExecutorServiceAdapter.kt:53)
	at com.android.build.gradle.internal.testing.BaseTestRunner.runTests(BaseTestRunner.java:199)
	at com.android.build.gradle.internal.tasks.DeviceProviderInstrumentTestTask.lambda$doTaskAction$2(DeviceProviderInstrumentTestTask.java:340)
	at com.android.builder.testing.api.DeviceProvider.use(DeviceProvider.java:53)
```

What am I missing here in regards to setting  `sdcard-path-or-size`?

**Comment by AaronMT** [comment]
What is the default `disk.dataPartition.size` for this AVD? Are we able to change this?

**Comment by efraespada** [comment]
Same problem here 😕

**Comment by agap** [comment]
I suggest everyone who stumbles upon this ticket to try out the newest test device images supported by the latest release of this action (see [2.21.0](https://github.com/ReactiveCircus/android-emulator-runner/releases/tag/v2.21.0))

It worked for me; I'm not getting this error while running my UI tests anymore! :tada:

**Comment by AaronMT** [comment]
Still seeing this on v2.21.0 unfortunately (e.g, https://github.com/mozilla-mobile/fenix/runs/4433056839?check_suite_focus=true)

**Comment by mrk-han** [comment]
Closing per https://github.com/ReactiveCircus/android-emulator-runner/pull/219
