### ISSUE TITLE
Gradle threw an error while downloading artifacts from the network

### ISSUE THREAD

**Issue by Kiruel** [ReactiveCircus/android-emulator-runner#208]
Hi, and thanks for this action :) ! I got some problem to run it, it works well on local. But when I use it in my CI I got this error:

```bash
/bin/sh -c flutter drive --driver=test_driver/integration_test.dart --target=integration_test/login_success_test.dart

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Running "flutter pub get" in flutter_tools...                       5.5s
WARNING | /etc/localtime does not point to zoneinfo-compatible timezone name
Running "flutter pub get" in example...                             9.5s
Running Gradle task 'assembleDebug'...                          
Exception in thread "main" java.io.FileNotFoundException: ***/wrapper/dists/gradle-7.2-all/260hg96vuh6ex27h9vo47iv4d/gradle-7.2-all.zip.lck (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:49)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleDebug'...                           1,223ms
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Running Gradle task 'assembleDebug'...                          
Exception in thread "main" java.io.FileNotFoundException: ***/wrapper/dists/gradle-7.2-all/260hg96vuh6ex27h9vo47iv4d/gradle-7.2-all.zip.lck (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:49)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleDebug'...                             882ms
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Gradle task assembleDebug failed with exit code 1
Error: The process '/bin/sh' failed with exit code 1
/Users/runner/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu kill
OK: killing emulator, bye bye
OK
INFO    | Discarding the changed state: command-line flag
WARNING | Discarding the changed state (command-line flag).
```
Anyone can help me with that?

The action I use:
```yaml
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: ${{ matrix.target }}
          arch: x86_64
          working-directory: ${{ matrix.path }}
          api-level: ${{ matrix.api-level }}
          script: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/login_success_test.dart
```

**Comment by Kiruel** [comment]
Use sudo before flutter drive fix the problem. But we should find a better way.

**Comment by Kiruel** [comment]
The problem was my GRADLE_USER_HOME, my CI overriden this env and the action fail because of that. Fixed by just removing this ENV.
