### ISSUE TITLE
INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package signatures do not match previously installed version

### ISSUE THREAD

**Issue by hb0** [ReactiveCircus/android-emulator-runner#319]
We're using this Github Action to execute our connected tests.
This worked nicely, also after adding the AVD cache like described in the guide.

But after a few executions on multiple branches, we now get the following error (in both, our library project [android-backend](https://github.com/cyface-de/android-backend/actions/runs/4184808537/jobs/7250971487) and our app project [android-app](https://github.com/cyface-de/android-app/actions/runs/4183661789/jobs/7249443800):

```
> Task :submodule:connectedDebugAndroidTest
additionalTestOutput is not supported on this device running API level 28 because the additional test output directory could not be found
2023-02-15 14:25:01.135 qemu-system-x86_64[3763:12[599](https://github.com/org/repo/actions/runs/4184808537/jobs/7250971487#step:8:603)] [CAMetalLayer nextDrawable] returning nil because device is nil.
2023-02-15 14:25:01.283 qemu-system-x86_64[3763:12599] [CAMetalLayer nextDrawable] returning nil because device is nil.
2023-02-15 14:25:01.335 qemu-system-x86_64[3763:12599] [CAMetalLayer nextDrawable] returning nil because device is nil.
Exception thrown during onBeforeAll invocation of plugin com.google.testing.platform.plugin.android.AndroidDevicePlugin.
Failed to install APK(s): /Users/runner/work/android-backend/android-backend/submodule/build/outputs/apk/androidTest/debug/submodule-debug-androidTest.apk
INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.example.submodule.test signatures do not match previously installed version; ignoring!
com.android.ddmlib.InstallException: INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.examble.submodule.test signatures do not match previously installed version; ignoring!
	at com.android.ddmlib.internal.DeviceImpl.installRemotePackage(DeviceImpl.java:1315)
	at com.android.ddmlib.internal.DeviceImpl.installPackage(DeviceImpl.java:1141)
	at com.android.tools.utp.plugins.deviceprovider.ddmlib.DdmlibAndroidDevice.installPackage(DdmlibAndroidDevice.kt)
	at com.android.tools.utp.plugins.deviceprovider.ddmlib.DdmlibAndroidDeviceController$executeAsync$deferred$1.invokeSuspend(DdmlibAndroidDeviceController.kt:173)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

I haven't found an issue in this repository for that error yet, so I'm posting this also for future readers.

When I execute the same Github Action again, the same error occurs.

The caches look like this:
![Screenshot from 2023-02-15 15-37-45](https://user-images.githubusercontent.com/6112241/219058222-775af1c9-08bc-48ef-963f-7aefd327de23.png)

When I remove all caches and [execute the Workflow again](https://github.com/cyface-de/android-backend/actions/runs/4184896896), the error disappears.

You can checkout the workflow [here](https://github.com/cyface-de/android-backend/blob/main/.github/workflows/gradle_connected-tests.yml), the relevant part is:

```
jobs:
  build:
    runs-on: macos-latest # as recommended in `actions/android-emulator-runner`

    strategy:
      matrix:
        api-level: [ 28 ]

(...)

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          disable-animations: true
          script: echo "Generated AVD snapshot for caching."

      - name: Connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save
          disable-animations: true
          script: ./gradlew :persistence:connectedDebugAndroidTest :datacapturing:connectedCyfaceMockDebugAndroidTest :synchronization:connectedCyfaceMockDebugAndroidTest :datacapturing:connectedMovebisMockDebugAndroidTest :synchronization:connectedMovebisMockDebugAndroidTest
```

Did anyone see this issue before and / or has an idea how what's going wrong here?
My first guess would be that the cached AVD is not fully cleared before it's pushed to the cache?

**Comment by Hatzen** [comment]
I have faced this issue with explorativ tests when i tried to install an older verison of this apk.  
I guess this error wont appear if u automatically increase the apk version before running the test

**Comment by AnandaDwiprayoga** [comment]
+1, i'm also faced this issue after adding AVD cache
