### ISSUE TITLE
com.google.android.gms/.auth.login.LoginActivity

### ISSUE THREAD

**Issue by UnityGitApps** [ReactiveCircus/android-emulator-runner#345]
Exception occurred while executing 'start':
java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.google.android.gms/.auth.login.LoginActivity } from null (pid=2023, uid=2000) not exported from uid 10106
	at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1110)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1024)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:713)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1292)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1233)
	at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:3139)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:603)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:208)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:9197)
	at android.os.Binder.shellCommand(Binder.java:1049)
	at android.os.Binder.onTransact(Binder.java:877)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4731)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2630)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1244)

**Comment by UnityGitApps** [comment]
all good
