### ISSUE TITLE
How to get more detail from failed tests?

### ISSUE THREAD

**Issue by merlinpaypal** [ReactiveCircus/android-emulator-runner#361]
I just stared using android-emulator-runner and love how easy it is to set up.

Is there a way to get more detail about failed tests?

The current output just says a test fails but doesn't tell me which assertion it fails on.

It also doesn't tell me how many other tests pass.

Also is there any way to get the test output to post to the PR as a comment?

This is my current output

```
> Task :library:connectedDebugAndroidTest
additionalTestOutput is not supported on this device running API level 23 because the additional test output directory could not be found

[DDMLIB]: An unexpected packet was received before the handshake.
[DDMLIB]: An unexpected packet was received before the handshake.

> Task :library:connectedDebugAndroidTest
Starting 23 tests on test(AVD) - 6.0

com.paypal.messages.io.ApiTest > testCreateMessageDataRequestWithAllData[test(AVD) - 6.0] FAILED 
	java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)

com.paypal.messages.io.ApiTest > testCreateMessageDataRequestWithNoData[test(AVD) - 6.0] FAILED 
	java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)

com.paypal.messages.logger.LoggerTest > testLog[test(AVD) - 6.0] FAILED 
	java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
Tests on test(AVD) - 6.0 failed: There was 3 failure(s).
```

**Comment by andreynovikov** [comment]
Same problem. I have another error ('attach to root') but there is no way to understand where exactly test fails. Difficulty is that with the same AVD image it passes without errors locally.

**Comment by johnjohndoe** [comment]
Did you try out other assertion libraries, e.g. [Google Truth](https://truth.dev/)? They might output more details.

**Comment by max-b** [comment]
In case anyone comes across this later, I found the answer [here](https://stackoverflow.com/a/37780887/1787596) useful by running logcat in the background:
```
  script: adb logcat "System.out:D YOUR_LOG_TAG_HERE:D *:S" & LOGCAT_PID=$! ; ./gradlew connectedAndroidTest ; test_ret=$? ; if [ -n "$LOGCAT_PID" ] ; then kill $LOGCAT_PID; fi; exit $test_ret
```
