### ISSUE TITLE
Getting error while starting emulator 

### ISSUE THREAD

**Issue by GauravP123** [ReactiveCircus/android-emulator-runner#52]
Hi 
Getting following error 
`Run reactivecircus/android-emulator-runner@v2
You're running a Linux VM where hardware acceleration is not available. Please consider using a macOS VM instead to take advantage of native hardware acceleration support provided by HAXM.
API level: 27
target: default
CPU architecture: x86
Hardware profile: 
emulator options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
disable animations: true
Script:
fastlane app
Installing new cmdline-tools.
sudo mkdir undefined/cmdline-tools
mkdir: cannot create directory ‘undefined/cmdline-tools’: No such file or directory`

yml looks like 

name: Testing CI

on:
  push:
    branches:
      - test
jobs:
  build:
    name: Unit Test
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2

        with:
          api-level: 27
          arch: x86
          script: fastlane app

**Comment by ychescale9** [comment]
Hmm I haven't tested with `self-hosted ` VMs, and the issue is likely caused by the environment variables / paths on your hosted VM being different from the `ubuntu` one which already have most of the Android SDK tools installed. Can you try the same config with `ubuntu-latest`?

**Comment by GauravP123** [comment]
i tired on maco-latest  its not giving at above issue ,
but getting 
`No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
`
the same test suite if I run on the local machine it's working

**Comment by ychescale9** [comment]
I wonder if it's `fastlane`, any chance you can try with `./gradlew connectedCheck` instead of `fastlane app`?

**Comment by GauravP123** [comment]
i tried with ./gradlew connectedCheck same result

**Comment by ychescale9** [comment]
Can you do `./gradlew connectedCheck --stacktrace` and share the full log?

**Comment by GauravP123** [comment]
2020-04-15T05:44:21.7460190Z org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:connectedCheck'.
2020-04-15T05:44:21.7460630Z 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:151)
2020-04-15T05:44:21.7461000Z 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:148)
2020-04-15T05:44:21.7461360Z 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
2020-04-15T05:44:21.7461710Z 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:141)
2020-04-15T05:44:21.7462080Z 	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
2020-04-15T05:44:21.7462450Z 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
2020-04-15T05:44:21.7463050Z 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
2020-04-15T05:44:21.7463520Z 	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
2020-04-15T05:44:21.7464070Z 	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
2020-04-15T05:44:21.7464440Z 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
2020-04-15T05:44:21.7464830Z 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
2020-04-15T05:44:21.7465210Z 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
2020-04-15T05:44:21.7465590Z 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
2020-04-15T05:44:21.7465970Z 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
2020-04-15T05:44:21.7466330Z 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
2020-04-15T05:44:21.7466690Z 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
2020-04-15T05:44:21.7467190Z 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
2020-04-15T05:44:21.7467570Z 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
2020-04-15T05:44:21.7467930Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
2020-04-15T05:44:21.7468460Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
2020-04-15T05:44:21.7468930Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
2020-04-15T05:44:21.7469290Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
2020-04-15T05:44:21.7469650Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
2020-04-15T05:44:21.7470010Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
2020-04-15T05:44:21.7470640Z 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
2020-04-15T05:44:21.7471000Z 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
2020-04-15T05:44:21.7471380Z 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
2020-04-15T05:44:21.7471750Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
2020-04-15T05:44:21.7472120Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
2020-04-15T05:44:21.7472590Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
2020-04-15T05:44:21.7472970Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
2020-04-15T05:44:21.7473340Z 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
2020-04-15T05:44:21.7473760Z 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
2020-04-15T05:44:21.7474340Z 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
2020-04-15T05:44:21.7474780Z 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
2020-04-15T05:44:21.7475140Z 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
2020-04-15T05:44:21.7475490Z 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
2020-04-15T05:44:21.7475840Z 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
2020-04-15T05:44:21.7476210Z 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
2020-04-15T05:44:21.7476590Z Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///Users/runner/runners/2.168.0/work/Android/app/build/reports/androidTests/connected/flavors/PROSTAGING/index.html
2020-04-15T05:44:21.7477010Z 	at com.android.build.gradle.internal.tasks.DeviceProviderInstrumentTestTask.doTaskAction(DeviceProviderInstrumentTestTask.java:226)
2020-04-15T05:44:21.7477390Z 	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:51)
2020-04-15T05:44:21.7477750Z 	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:31)
2020-04-15T05:44:21.7478100Z 	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:91)
2020-04-15T05:44:21.7478450Z 	at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:34)
2020-04-15T05:44:21.7478800Z 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
2020-04-15T05:44:21.7479150Z 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
2020-04-15T05:44:21.7479500Z 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
2020-04-15T05:44:21.7479860Z 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
2020-04-15T05:44:21.7480200Z 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:702)
2020-04-15T05:44:21.7480550Z 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:669)
2020-04-15T05:44:21.7480900Z 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:404)
2020-04-15T05:44:21.7481270Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
2020-04-15T05:44:21.7489970Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
2020-04-15T05:44:21.7490170Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
2020-04-15T05:44:21.7509410Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
2020-04-15T05:44:21.7509890Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
2020-04-15T05:44:21.7510300Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
2020-04-15T05:44:21.7510680Z 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
2020-04-15T05:44:21.7511060Z 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:393)
2020-04-15T05:44:21.7511460Z 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:376)
2020-04-15T05:44:21.7511840Z 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:80)
2020-04-15T05:44:21.7512520Z 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:213)
2020-04-15T05:44:21.7512980Z 	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
2020-04-15T05:44:21.7513340Z 	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
2020-04-15T05:44:21.7513680Z 	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
2020-04-15T05:44:21.7514130Z 	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
2020-04-15T05:44:21.7514500Z 	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
2020-04-15T05:44:21.7514850Z 	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
2020-04-15T05:44:21.7515190Z 	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
2020-04-15T05:44:21.7515540Z 	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
2020-04-15T05:44:21.7515890Z 	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
2020-04-15T05:44:21.7516230Z 	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
2020-04-15T05:44:21.7516560Z 	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
2020-04-15T05:44:21.7516900Z 	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
2020-04-15T05:44:21.7517260Z 	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
2020-04-15T05:44:21.7517620Z 	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
2020-04-15T05:44:21.7517960Z 	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:201)
2020-04-15T05:44:21.7518300Z 	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
2020-04-15T05:44:21.7518640Z 	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
2020-04-15T05:44:21.7519010Z 	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
2020-04-15T05:44:21.7519360Z 	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
2020-04-15T05:44:21.7519700Z 	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
2020-04-15T05:44:21.7520040Z 	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
2020-04-15T05:44:21.7521030Z 	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
2020-04-15T05:44:21.7521450Z 	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
2020-04-15T05:44:21.7521810Z 	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
2020-04-15T05:44:21.7522160Z 	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
2020-04-15T05:44:21.7522510Z 	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
2020-04-15T05:44:21.7522850Z 	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:77)
2020-04-15T05:44:21.7523190Z 	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
2020-04-15T05:44:21.7523540Z 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
2020-04-15T05:44:21.7523910Z 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
2020-04-15T05:44:21.7524260Z 	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
2020-04-15T05:44:21.7524800Z 	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
2020-04-15T05:44:21.7525250Z 	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
2020-04-15T05:44:21.7525610Z 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:120)
2020-04-15T05:44:21.7525940Z 	... 35 more
2020-04-15T05:44:21.7526190Z

**Comment by ychescale9** [comment]
Thanks but this doesn't look like the full GitHub Actions log?

Can you attach the full log file?

<img width="252" alt="Screen Shot 2020-04-15 at 5 40 04 pm" src="https://user-images.githubusercontent.com/11519072/79311080-3dd19000-7f40-11ea-96af-4b1518a65a26.png">
